In [3]:
%pip install numpy pandas

Collecting numpy
  Downloading numpy-2.5.2-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading numpy-2.5.2-cp314-cp314-macosx_14_0_arm64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 4.4 MB/s  0:00:01 eta 0:00:01
Downloading pandas-3.0.5-cp314-cp314-macosx_11_0_arm64.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 2.7 MB/s  0:00:03eta 0:00:01
Installing collected packages: numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]2m1/2 [pandas]
Successfully installed numpy-2.5.2 pandas-3.0.5
Note: you may need to restart the kernel to use updated packages.

In [4]:
import numpy as pd
import pandas as pd

# Series: Population by Country Code
country_population = pd.Series(
data=[61, 46, 11, 65, 10],
index=["IT", "ES", "GR", "FR", "PO"],
name="Country Population"
)
country_population
data = {
"Name": [
"Avery Bradley", "John Holland", "Jonas Jerebko",
"Jordan Mickey", "Terry Rozier", "Jared Sullinger", "Evan Turner"
],
"Team": ["Boston Celtics"] * 7,
"Number": [0.0, 30.0, 8.0, None, 12.0, 7.0, 11.0],
"Position": ["PG", "SG", "PF", "PF", "PG", "C", "SG"],
"Age": [25.0, 27.0, 29.0, 21.0, 22.0, None, 27.0]
}
df_0 = pd.DataFrame(data)

In [5]:
country_population.index

Index(['IT', 'ES', 'GR', 'FR', 'PO'], dtype='str')

In [ ]:
country_population[1]

/tmp/ipykernel_1634/2605600934.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  country_population[1]

np.int64(46)

In [ ]:
country_population['GR']

np.int64(11)

In [ ]:
country_population[:'GR']

IT    61
ES    46
GR    11
Name: Country Population, dtype: int64

In [ ]:
df_0

              Name            Team  Number Position   Age
0    Avery Bradley  Boston Celtics     0.0       PG  25.0
1     John Holland  Boston Celtics    30.0       SG  27.0
2    Jonas Jerebko  Boston Celtics     8.0       PF  29.0
3    Jordan Mickey  Boston Celtics     NaN       PF  21.0
4     Terry Rozier  Boston Celtics    12.0       PG  22.0
5  Jared Sullinger  Boston Celtics     7.0        C   NaN
6      Evan Turner  Boston Celtics    11.0       SG  27.0

In [ ]:
df_0['Name']

0      Avery Bradley
1       John Holland
2      Jonas Jerebko
3      Jordan Mickey
4       Terry Rozier
5    Jared Sullinger
6        Evan Turner
Name: Name, dtype: object

In [ ]:
df_0['Number']

0     0.0
1    30.0
2     8.0
3     NaN
4    12.0
5     7.0
6    11.0
Name: Number, dtype: float64

In [ ]:
df_0.iloc[:2,:3]

            Name            Team  Number
0  Avery Bradley  Boston Celtics     0.0
1   John Holland  Boston Celtics    30.0

In [ ]:
df_0['Age']>22

0     True
1     True
2     True
3    False
4    False
5    False
6     True
Name: Age, dtype: bool

In [ ]:
df_0[df_0['Age']>22]

            Name            Team  Number Position   Age
0  Avery Bradley  Boston Celtics     0.0       PG  25.0
1   John Holland  Boston Celtics    30.0       SG  27.0
2  Jonas Jerebko  Boston Celtics     8.0       PF  29.0
6    Evan Turner  Boston Celtics    11.0       SG  27.0