# Lesson 06 - Tutorial
## Outliers & Missing Data

**Instruction:**  
- Complete the hand calculations first.  
- Then fill in the empty code cells.  
- Required libraries and toy datasets are already provided.

## 0. Import packages

In [1]:
import numpy as np
import pandas as pd

from sklearn.neighbors import LocalOutlierFactor
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer, KNNImputer

ModuleNotFoundError: No module named 'sklearn'

# Exercise 1. LOF – Distances

Use the dataset below with $k=2$.

$$
d(i,j)=\sqrt{(x_{i1}-x_{j1})^2+(x_{i2}-x_{j2})^2}
$$

### Tasks
1. Calculate the pairwise distances by hand.
2. Identify the 2 nearest neighbors of each point.
3. Fill in the code cell to verify your answers.

In [2]:
X_lof = pd.DataFrame({
    'X1': [12, 15, 12, 27],
    'X2': [8, 8, 11, 8]
}, index=['A', 'B', 'C', 'P'])

X_lof

   X1  X2
A  12   8
B  15   8
C  12  11
P  27   8

In [ ]:
# TODO: calculate pairwise Euclidean distances

# Exercise 2. LOF – Reachability, LRD and LOF

Use:

- $k\text{-dist}(A)=3.00$
- $k\text{-dist}(B)=4.24$
- $k\text{-dist}(C)=4.24$
- $k\text{-dist}(P)=15.00$

$$
rd_k(p,o)=\max\{k\text{-dist}(o),d(p,o)\}
$$

$$
LRD_k(p)=\frac{|N_k(p)|}{\sum_{o\in N_k(p)}rd_k(p,o)}
$$

$$
LOF_k(p)=\frac{1}{|N_k(p)|}\sum_{o\in N_k(p)}\frac{LRD_k(o)}{LRD_k(p)}
$$

### Tasks
1. Calculate reachability distances by hand.
2. Calculate LRD for A, B, C, P.
3. Calculate LOF(P).
4. Use Python to verify.

In [3]:
# TODO: fit LOF with n_neighbors=2
# TODO: create LOF scores and labels

# Exercise 3. `n_neighbors` and `contamination`

### Tasks
1. Explain `n_neighbors=2`.
2. Explain `contamination=0.10`.
3. Compare LOF results when $k=2,3,4$.

In [4]:
toy = pd.DataFrame({
    'x': [2.0, 2.1, 1.9, 2.2, 2.0, 7.0],
    'y': [3.0, 3.2, 2.8, 3.1, 3.0, 8.0]
})

toy

     x    y
0  2.0  3.0
1  2.1  3.2
2  1.9  2.8
3  2.2  3.1
4  2.0  3.0
5  7.0  8.0

In [ ]:
# TODO: run LOF for k = 2, 3, 4
# Hint: use a for loop

# Exercise 4. Scaling before LOF

### Tasks
1. Identify which variable may dominate Euclidean distance.
2. Standardize the variables.
3. Compare the original and standardized data.

In [5]:
df_scale = pd.DataFrame({
    'income': [45, 50, 55, 90],
    'debt_ratio': [0.25, 0.30, 0.28, 0.85],
    'score': [690, 710, 705, 500]
}, index=['A', 'B', 'C', 'P'])

df_scale

   income  debt_ratio  score
A      45        0.25    690
B      50        0.30    710
C      55        0.28    705
P      90        0.85    500

In [ ]:
# TODO: standardize df_scale using StandardScaler

# Exercise 5. Missing-value audit

### Tasks
1. Count missing values by column.
2. Count missing values by row.
3. Identify complete rows.
4. Compute the retention rate after `dropna()`.

In [6]:
df = pd.DataFrame({
    'id': [1, 2, 3, 4, 5],
    'income': [50, 65, 72, 88, 60],
    'debt_ratio': [0.30, 0.40, np.nan, 0.55, 0.35],
    'credit_score': [700, np.nan, 680, 640, 710],
    'loan_amount': [120, 150, 140, 210, np.nan]
})

df

   id  income  debt_ratio  credit_score  loan_amount
0   1      50        0.30         700.0        120.0
1   2      65        0.40           NaN        150.0
2   3      72         NaN         680.0        140.0
3   4      88        0.55         640.0        210.0
4   5      60        0.35         710.0          NaN

In [ ]:
# TODO: count missing values by column

In [ ]:
# TODO: count missing values by row

In [ ]:
# TODO: drop incomplete rows and calculate retention rate

# Exercise 6. Mean imputation

Observed `credit_score` values are:

$$
700,\ 680,\ 640,\ 710
$$

### Tasks
1. Calculate the mean by hand.
2. Use `SimpleImputer(strategy='mean')`.
3. Compare the Python result with your hand calculation.

In [10]:
# TODO: create and fit a SimpleImputer with strategy='mean'
# TODO: impute credit_score

imp_mean = SimpleImputer(strategy='mean')

df_mean=df.copy()
df_mean[['credit_score']] = imp_mean.fit_transform(
    df[['credit_score']]
)

print("Mean:",imp_mean.statistics_[0])
display(df_mean)

Mean: 682.5

   id  income  debt_ratio  credit_score  loan_amount
0   1      50        0.30         700.0        120.0
1   2      65        0.40         682.5        150.0
2   3      72         NaN         680.0        140.0
3   4      88        0.55         640.0        210.0
4   5      60        0.35         710.0          NaN

In [9]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

# Tạo dữ liệu mẫu chứa các giá trị quan sát và một giá trị khuyết (np.nan)
data = np.array([[700], [680], [640], [710], [np.nan]])

# Khởi tạo SimpleImputer với chiến lược tính 'mean'
imputer = SimpleImputer(strategy='mean')

# Fit mô hình và biến đổi dữ liệu
imputed_data = imputer.fit_transform(data)

# In giá trị trung bình mà SimpleImputer đã học được
print(f"Giá trị trung bình được tính bởi SimpleImputer: {imputer.statistics_[0]}")

# Hiển thị mảng sau khi đã điền giá trị khuyết
print("\nDữ liệu sau khi điền khuyết thiếu:")
print(imputed_data)

Giá trị trung bình được tính bởi SimpleImputer: 682.5

Dữ liệu sau khi điền khuyết thiếu:
[[700. ]
 [680. ]
 [640. ]
 [710. ]
 [682.5]]

# Exercise 7. Mean vs Median

Data:

$$
35,\ 40,\ 45,\ 50,\ 250,\ NaN
$$

### Tasks
1. Calculate the mean by hand.
2. Calculate the median by hand.
3. Impute with mean.
4. Impute with median.
5. Compare the two results.

In [ ]:
x = pd.DataFrame({
    'income': [35, 40, 45, 50, 250, np.nan]
})

x

In [ ]:
# TODO: mean imputation

In [ ]:
# TODO: median imputation

# Exercise 8. Mode imputation

Data:

`Private, FDI, Private, State, Private, NaN`

### Tasks
1. Find the mode by hand.
2. Use `SimpleImputer(strategy='most_frequent')`.

In [ ]:
sector = pd.DataFrame({
    'sector': ['Private', 'FDI', 'Private', 'State', 'Private', np.nan]
})

sector

In [ ]:
# TODO: mode imputation

# Exercise 9. KNNImputer – Find Neighbors

Use $k=2$.

$$
d(P,i)=|55-X_i|
$$

### Tasks
1. Calculate distances from P to A, B, C, D.
2. Identify the 2 nearest neighbors.
3. Verify with Python.

In [ ]:
df_knn = pd.DataFrame({
    'income': [40, 50, 55, 60, 80],
    'score': [730, 710, np.nan, 690, 650]
}, index=['A', 'B', 'P', 'C', 'D'])

df_knn

In [ ]:
# TODO: calculate distances from P to A, B, C, D

# Exercise 10. KNNImputer – Uniform Weights

Nearest neighbors:

- B: score = 710
- C: score = 690

$$
\hat{Y}_P=\frac{710+690}{2}
$$

### Tasks
1. Calculate the result by hand.
2. Verify using `KNNImputer(n_neighbors=2, weights='uniform')`.

In [ ]:
# TODO: KNN imputation with uniform weights

# Exercise 11. KNNImputer – Distance Weights

For P:

- $d(P,B)=5$
- $d(P,C)=5$

$$
w_i=\frac{1}{d_i}
$$

$$
\hat{Y}_P=
\frac{w_B(710)+w_C(690)}
{w_B+w_C}
$$

### Tasks
1. Calculate the result by hand.
2. Verify using `weights='distance'`.
3. Compare with Exercise 10.

In [ ]:
# TODO: KNN imputation with distance weights

# Exercise 12. Iterative Imputation

| ID | X1 | X2 | X3 |
|---|---:|---:|---:|
| A | NaN | 2 | 4 |
| B | 3 | NaN | 6 |
| C | 5 | 5 | NaN |

Assume:

$$
X_1=X_2
$$

$$
X_3=2X_1
$$

### Tasks
1. Calculate initial column means.
2. Impute the missing values by hand.
3. Use `IterativeImputer` to verify.

In [ ]:
mice_toy = pd.DataFrame({
    'X1': [np.nan, 3.0, 5.0],
    'X2': [2.0, np.nan, 5.0],
    'X3': [4.0, 6.0, np.nan]
}, index=['A', 'B', 'C'])

mice_toy

In [ ]:
# TODO: calculate initial column means

In [ ]:
# TODO: import IterativeImputer and an estimator
# TODO: fit and transform mice_toy

In [ ]:
# TODO: fit SimpleImputer on X_train only
# TODO: transform X_train and X_test